[package]
name = "feedback_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"
actix-cors = "0.6"
